# Generated by Django 5.0 on 2025-03-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserFacing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
