# Generated by Django 5.0 on 2025-03-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_image', models.ImageField(default='app_images/default.jpg', upload_to='app_images/')),
                ('app_name', models.CharField(max_length=255, unique=True)),
                ('download_link', models.URLField()),
                ('app_category', models.CharField(default='', max_length=255)),
                ('subcategory', models.CharField(default='', max_length=255)),
                ('points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
