# Generated by Django 5.0 on 2025-03-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminFacing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_category',
            field=models.CharField(choices=[('Social Media', 'Social Media'), ('Entertainment', 'Entertainment'), ('Communication', 'Communication'), ('Productivity', 'Productivity'), ('Education', 'Education')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='app',
            name='subcategory',
            field=models.CharField(choices=[('Social Networking', 'Social Networking'), ('Messaging', 'Messaging'), ('Content Sharing', 'Content Sharing'), ('Professional Networking', 'Professional Networking'), ('Community', 'Community'), ('Task Management', 'Task Management'), ('Music', 'Music'), ('Learning', 'Learning')], default='', max_length=255),
        ),
    ]
